# Generated by Django 3.2.7 on 2021-09-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nci', models.CharField(max_length=10)),
                ('number_phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('url_client', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CodeLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_licence', models.CharField(max_length=200)),
                ('type_licence', models.IntegerField(null=True)),
                ('create_at', models.DateTimeField()),
                ('licences', models.ManyToManyField(related_name='licence', related_query_name='licence', to='licence.Client')),
            ],
        ),
    ]
