# Generated by Django 3.2.7 on 2021-09-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0002_auto_20210918_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelicence',
            name='licences',
            field=models.ManyToManyField(related_name='licences', to='licence.Client'),
        ),
    ]
