# Generated by Django 3.2.7 on 2021-09-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0003_alter_codelicence_licences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codelicence',
            name='licences',
        ),
        migrations.AddField(
            model_name='client',
            name='licences',
            field=models.ManyToManyField(related_name='licences', to='licence.CodeLicence'),
        ),
    ]
